name: weather_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  animate_do: ^3.1.2
  intl: ^0.19.0
  flutter:
    sdk: flutter
  weather_animation: ^1.0.1
  flutter_dotenv: ^5.1.0
  http: ^1.1.2
  provider: ^6.1.1
  blur: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - lib/images/cloud and sun.png
    - lib/images/cloudy.png
    - lib/images/raining.png
    - lib/images/sunny.png
    - lib/images/thunderstorm.png
